[project]
name = "estimate-qubit-frequency"
version = "0.1.0"
dependencies = [
  "numpy",
  "scipy",
  "plotly",
  "kaleido",
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
  "scipy-stubs",
]
